
---

apiVersion: v1
kind: Service
metadata:
    name: votingapp-service
    labels:
     app: votingapp
     name: votingapp-service

spec:
      type: LoadBalancer
      ports:
      - protocol: TCP
        port: 80
        targetPort: 80

      selector:
        app: votingapp
        name: votingapp-pod
      
