---

apiVersion: v1
kind: Pod
metadata:
   name: votingapp-pod
   labels:
      app: votingapp
      name: votingapp-pod

spec:
   containers:
    - name: voting-appcont
      image: dockersamples/examplevotingapp_vote:before
      ports:
        - containerPort: 80
